# Generated by Django 5.2.5 on 2025-08-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimiento',
            old_name='mecanico',
            new_name='mecánico',
        ),
        migrations.RenameField(
            model_name='procedimiento',
            old_name='vehiculo',
            new_name='vehículo',
        ),
    ]
