# Generated by Django 5.2.5 on 2025-08-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimiento', '0002_rename_mecanico_procedimiento_mecánico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimiento',
            old_name='mecánico',
            new_name='mecanico',
        ),
        migrations.RenameField(
            model_name='procedimiento',
            old_name='vehículo',
            new_name='vehiculo',
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
