# Generated by Django 5.2.5 on 2025-08-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehículo',
            old_name='anio',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='vehículo',
            old_name='dueno',
            new_name='dueño',
        ),
    ]
